export const BUTTONS_FUNCTIONS = [
  {label: 'Click izquierdo', value: '1'},
  {label: 'Click derecho', value: '2'},
  {label: 'Click central', value: '3'},
  {label: 'Barra espaciadora', value: '4'},
  {label: 'Tecla enter', value: '5'},
  {label: 'Doble click', value: '6'},
  {label: 'Una letra', value: '7'},
  {label: 'Nada (anular botón)', value: '8'},
]

export const CHARACTERS = [
  {label: 'a', value: 'a'},
  {label: 'b', value: 'b'},
  {label: 'c', value: 'c'},
  {label: 'd', value: 'd'},
  {label: 'e', value: 'e'},
  {label: 'f', value: 'f'},
  {label: 'g', value: 'g'},
  {label: 'h', value: 'h'},
  {label: 'i', value: 'i'},
  {label: 'j', value: 'j'},
  {label: 'k', value: 'k'},
  {label: 'l', value: 'l'},
  {label: 'm', value: 'm'},
  {label: 'n', value: 'n'},
  {label: 'ñ', value: 'ñ'},
  {label: 'o', value: 'o'},
  {label: 'p', value: 'p'},
  {label: 'q', value: 'q'},
  {label: 'r', value: 'r'},
  {label: 's', value: 's'},
  {label: 't', value: 't'},
  {label: 'u', value: 'u'},
  {label: 'v', value: 'v'},
  {label: 'w', value: 'w'},
  {label: 'x', value: 'x'},
  {label: 'y', value: 'y'},
  {label: 'z', value: 'z'},
  {label: '0', value: '0'},
  {label: '1', value: '1'},
  {label: '2', value: '2'},
  {label: '3', value: '3'},
  {label: '4', value: '4'},
  {label: '5', value: '5'},
  {label: '6', value: '6'},
  {label: '7', value: '7'},
  {label: '8', value: '8'},
  {label: '9', value: '9'},
]
